### ISSUE TITLE
OS X bash 3.2 doesn't run the bash completion

### ISSUE THREAD

**Issue by sscherfke** [sashahart/vex#23]
`eval "$(vex --shell-config bash)"` prints an error when executed with the OS X (10.9) default bash:

```
syntax error in conditional expression: unexpected token `('
syntax error near `@($'
`			if [[ "${prev}" != @($take_args) ]]; then'
```
I think this is because OS X still uses bash 3.2. I don't get this error on Linux with bash 4.3.

**Comment by glyph** [comment]
@sashahart - if you are interested in continuous integration, Travis does offer multi-OS builds, so it's possible to get free OS X testing...

Until recently I was using vex both with bash from OS X and bash from MinGW32 which is even *more* impressively ancient - bash 3.0 :-).  These are exactly the audiences who could benefit the most from vex, since virtualenvwrapper is quite confusing for beginners…

**Comment by glyph** [comment]
It appears that this is not a bash 3.2 issue so much as a "completion support must already be sourced" issue.  It depends on the `bash-completion` package from homebrew, in other words, not the `bash` package; with that installed, vex's completion seems to be working.  I don't quite understand how this is possible, given that it's a *syntax* error and not a missing command or variable, but I will let you know if I come up with anything.

**Comment by sashahart** [comment]
After trying whatever bash 3.2 I could get my hands on without replicating, I won't be surprised if it has something to do with a platform-specific build or configs rather than the version.

If the homebrew bash-completion package solves this somehow, it's particularly confusing that this would appear as a syntax error. I wonder what the homebrew package for bash-completion is really doing relative to the default bash for OS X. 

Being able to check for the condition at the root of sscherfke's symptom would at least make it possible to provide a slightly more helpful message than that opaque syntax error. 

I've made abortive attempts to replicate the complaint by messing up bash configs without much success, and will spend some more time next week on that since I'm also distantly concerned about the relevant variations the bash environment might suffer on other platforms.

This kind of investigation by OS X users is very helpful because it's an awkward kind of issue to track down without interactive access to a similarly configured system.

**Comment by sashahart** [comment]
In the interim or in the worst case, this can be mitigated slightly in the README. I'll entertain  amendments to https://github.com/sashahart/vex/pull/37 that would describe to OS X users what they should do, insofar as it's stuff vex can't reasonably do (like installing packages).
