### ISSUE TITLE
--remove deletes the env note before you leave it

### ISSUE THREAD

**Issue by KLINGTdotNET** [sashahart/vex#35]
When I use `vex --remove envname`, vex starts the virtualenv and then after leaving the environment, it will be removed. Vex should remove the virtual environment without starting it beforehand.

**Comment by sashahart** [comment]
vex is, by design, a tool for running commands in virtualenvs.

--make doesn't just make a virtualenv, it makes the virtualenv *and then runs your command in it*.

Similarly, --remove is *supposed* to remove the virtualenv after running whatever command you asked for.

This has intended use cases: for example I use vex -mr foo baz to just create a virtualenv, run baz and then tear down in one command.

--make and --remove would not exist at all except for this kind of use case. vex isn't a substitute for rm, cp, etc. 

You can remove virtualenvs with rm or trash-cli.

Thanks
